### ISSUE TITLE
Request: Agricraft changes

### ISSUE THREAD

**Issue by dewboy3d** [CaptainSilver/Double-Twix-pack-Issue-tracker#1]
Weed growth is happening extremely fast, especially under irrigation. Mutating and advancing crops is ridiculously difficult. I don't mind a time sink but I've wasted an entire stack of crop sticks for a single stat increase on my wheat seeds. 

In Config/Agricraft/json/vanilla/weed_plant.json set "enabled": false

Also, there are no tooltips for crops in HWYLA/WAWLA in 1.12. I suggest The One Proble as a replacement.

**Comment by CaptainSilver** [comment]
Removed weed growth(Nuisance form of grinding)
Removed HWYLA not all of the features that are present in previous versions of MC are still there, crippling the mod. The One probe is a good replacement. Done.
