### ISSUE TITLE
Request: More metals and dimension to quarry in

### ISSUE THREAD

**Issue by dewboy3d** [CaptainSilver/Double-Twix-pack-Issue-tracker#2]
I would like to recommend adding a mod to give some more metals for tinkers tools. 

Something like https://www.curseforge.com/minecraft/mc-mods/base-metals or another mod that adds common metals and is compatible with TiCon.

Also, I am just about getting ready to start building a quarry. It would be nice to not have large holes in the overworld. Can we get https://www.curseforge.com/minecraft/mc-mods/aroma1997s-dimensional-world or some similar alternate dimension for quarrying and mining?

Perhaps it's possible to limit ore gen from whichever mod to only spawn in the mining dimension.

**Comment by CaptainSilver** [comment]
Accepted will add mining dimension and find a mod with metals and uses for them.

**Comment by CaptainSilver** [comment]
Done added and restricted to the mining world
