### ISSUE TITLE
Request: Increase mutation chance for Agricraft crops

### ISSUE THREAD

**Issue by dewboy3d** [CaptainSilver/Double-Twix-pack-Issue-tracker#4]
The title says it. I think mutation chance is at 20%. Can we increase that? Maybe even double. Even without weeds on, crop advancement is tediously slow.

**Comment by CaptainSilver** [comment]
I'll change it, I'll see what modern skyblock 3 has it at.

**Comment by CaptainSilver** [comment]
Done, upped it from 15 to 30
